cms-kr/hep-tools

create-batch
Add VarPasing options for 72X runCat.py
=> Add VarPasing options.

create-batch
1. Add hostname display for debugging
2. Copying proxy CA need to be run before cmsRun
=> Display hostname and to fix to copy proxy CA before cmsRun.

create-batch, submitCondor, xrdls
1. Job manager is changed.
* UOS's  main job manager is changed to HTCondor. This PR included this change.
2. KISTI's xrd link is changed.
=> pbs to HTCondor at UOS. xrd directory is changed.

makeFileList
Add makeFileList to remove CatAnalyzer/scripts
=> Add makeFileList

makeFileList
=> loop over subdirectory one level

create-batch, makeFileList, xrdls
User can choose output file with "-o" option.
-o output.json will produce JSON file
and 
-o output.txt (or any other types) will produce output_0.txt... output_N.txt
=> support json and txt format

create-batch
=> bugfix by Youngkwon

xrdls
Fix the patch because of changing SE path.
=> Fix as path changing.

create-batch
Run on the EmptySource case, to be used in MC generation.
=> Run on EmptySource

dumpRoot
Add dumproot script which can simply dump all histograms in png format preserving TDirectory structure.
=> add dumproot

create-batch
User specfic bugfixes:
* two sys arguments to sync with usual cmsRun execution
* apply customise() while loading the cfg, not the "just before submit"
=> User specific bugfix

dumpRoot
Save TCanvas object from dumpRoot script.
=> save TCanvas

create-batch
Reduce the tar file size with better handling tar+gzip command
=> Reduce tar file size

copySubtree
=> Sub-tree only hadd

joinLumiJsonByAnd
Join two lumi json files by applying "and" filter.
=> new script to add lumi json

joinLumiJsonByAnd
=> bugfix to joinLumiJsonByAnd

runLumiCalc
Adding a script to run brilcalc.
This script does:
- install necessary packages in absence
- list up normtags
- run the brilcalc to get luminosity
=> brilcalc launcher

create-batch
=> Job splitting bugfix

runLumiCalc
turn on stable beam option as recommended.
=> stable beam option

create-batch
Retry file transfer after job finishes for 3 times.
=> Retry file transfer in temporary failures

crabmon
Reviving the crabmon GUI program to run on crab3.
=> Reviving crabmon for crab3

crabmon
=> crabmon missing commit

create-batch
create-batch is modified to run on EmptySource, enabling MC generation.
=> create-batch run on EmptySource for MC generation

create-batch
create batch works with eos command
Improve archiving, use root files under data directory only.
=> create-batch works with eos, improve archiving

create-batch
=> create-batch eos cp bugfix

create-batch
fix to copy output files to eos with xrd command
=> create-batch save output to eos

crabmon, create-batch
use crabAPI for crabmon command
additional option to set the run number, to be used in MC generation
=> Use crabAPI, create-batch to work with different runNumbers

crabsub
New crab GUI script to submit jobs
=> add new crab gui to submit jobs

haddFast
use xargs to run hadd with multiple CPUs
=> hadd use multiple CPUs

haddFast
=> hadd missing args

submitCondor
Add fileList option like as create-batch.
=> Add fileList option to submitCondor

crabmon
crabmon as a http service.
Runs as fall-back mode of original Tkinter based crabmon, or put --nogui option
Port number is set to 20000 by default in this version.
=> crabmon with HTTP

crabmon
crabAPI basically convenient, but simple log-analyzer is suitable when showing in web pages because of faster response from cached results.
=> Do not use crabAPI

crabmon
Set port number by user arguments.
=> crabmon set port number

crabmon, haddFast
crabmon web works with POST
haddFast update (was old update)
=> crabmon web with POST, haddFast update

crabmon
Crabmon web version prints out current working directory
=> crabmon web print out working directory

create-batch
simple bugfix to apply blacklist
=> create-batch blacklist bugfix

create-batch
missing "requirements" statement.
=> create-batch bugfix

haddsplit
haddsplit runs hadd but limiting the maximum size of the merged files to 4GByte.
=> new script to do hadd up to 4GByte

create-batch-lateSubmit
Adding a helper script, to submit jobs to the system waiting for the condor queue to be cool down.
=> Add create-batch-lateSubmit script

haddsplit
bugfix to treat single file haddsplit
=> haddsplit bugfix

create-batch
grid proxy part is fixed to run at lxbatch.
=> Better grid proxy

crabmon
crabmon was not working because of log msg format changes.
=> crabmon update

crabmon
=> crabmon bugfix

create-batch
Use pickle to dump python configuration file, will prevent python syntax error some cases.
=> create-batch use pickle

crabmon
crabmon watches directories given from arguments.
=> crabmon directory listing from arguments

create-batch
* Add whitelist option to create-batch to test specific machine.
=> Add whitelist option to create-batch

create-batch
Little bit better handling of whitelist
=> Better whitelist

create-batch
no picking and dumping for each sub job
makes job size much smalled
=> improve create-batch

create-batch
Support singularity environment at KISTI #78
=> support KISTI Singularity environment

create-batch
=> xrdcp for the KNU site

create-batch
Change default behaviour to turn on the grid certificate feature
=> Enable Grid certificate by default

create-batch
create directory via xrdfs command if not prepared yet
=> xrd-mkdir in the create-batch

create-batch
=> Bugfix typo

create-batch
Cleanup workarea when the job is finished.
=> clean up after job finishes

create-batch
Bugfix in the create-batch qsub/bsub command
=> create-batch bugfix add space in the qsub/bsub options

create-batch
create-batch is extended to support user scripts.
=> create-batch support for non-cmsRun jobs

create-batch
=> fix qsub option ordering

create-batch
KISTI T3 can use private network for the xrootd protocol.
=> kisti internal xrootd server

create-batch
=> fix remap string

create-batch
set condor batch_name to be the jobName
=> show batch name

create-batch
Keep python directory in the input archive file
=> Keep python directory in the archive

create-batch
Rebuild packages when job starts
=> Rebuild packages on start

create-batch
Additional tag to specify job submittor client application name.
=> Condor jds additional tag

create-batch
=> fix missing quote

checkDasDataSets
checks missing files from phedex transfers and gets them
=> checkDasDataSets script

create-batch
create-batch can select OS image, guessed from host OS envvar SCRAM_ARCH.
=> create-batch select OS image

create-batch
=> custom command to create output directory
